// Generated by CoffeeScript 1.9.2
(function() {
  var app, bodyParser, cookieParser, express, indexController, mongoConfig, mongoose, passport, port, server, session;

  express = require('express');

  bodyParser = require('body-parser');

  mongoose = require('mongoose');

  session = require('express-session');

  cookieParser = require('cookie-parser');

  passport = require('passport');

  mongoConfig = require('./config/mongo');

  indexController = require('./controllers/index');

  mongoose.connect(mongoConfig.stage || mongoConfig.dev);

  app = express();

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/views');

  app.use(express["static"](__dirname + '/public'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(session({
    secret: 'secret',
    resave: false,
    saveUninitialized: false
  }));

  app.use(passport.initialize());

  app.use(passport.session());

  app.get('/', indexController.index);

  port = process.env.PORT || 5150;

  server = app.listen(port, function() {
    return console.log("Express listening on port " + (server.address().port));
  });

  module.exports = app;

}).call(this);
