// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    index: function(req, res) {
      return res.render('main');
    },
    mainPage: function(req, res) {
      return res.render('main-page');
    }
  };

}).call(this);
