// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    test: 'mongodb://localhost/omb-test',
    dev: 'mongodb://localhost/omb',
    stage: process.env.MONGOLAB_URI
  };

}).call(this);
