// Generated by CoffeeScript 1.9.2
(function() {
  var LinedInStrategy, passport;

  passport = require('passport');

  LinedInStrategy = require('passport-linkedin-oauth2').Strategy;

  passport.use(new LinkedInStrategy);

}).call(this);
