// Generated by CoffeeScript 1.9.2
(function() {
  var mongoose, userSchema;

  mongoose = require('mongoose');

  userSchema = mongoose.Schema({
    profile: Object
  });

  module.exports = mongoose.model('user', userSchema);

}).call(this);
